<?php

namespace AppBundle\Repository;

/**
 * CatShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatShopRepository extends \Doctrine\ORM\EntityRepository
{
}
